# Generated by Django 3.2.6 on 2021-08-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210823_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='statut',
            field=models.CharField(choices=[('P', 'Provisoire'), ('R', 'Récupérée'), ('V', 'Vérifiée'), ('Q', 'Qualifiée')], default='Q', max_length=1, verbose_name="Statut d'identité"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='statut_compl',
            field=models.CharField(choices=[('H', 'Homonyme'), ('F', 'Fictive'), ('D', 'Douteuse')], default="F", max_length=1, verbose_name="Statut d'identité complémentaire"),
            preserve_default=False,
        ),
    ]
