# Generated by Django 3.2.6 on 2021-08-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210823_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='adresse_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='patient',
            name='adresse_line',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresse Ligne'),
        ),
        migrations.AddField(
            model_name='patient',
            name='adresse_pays',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='patient',
            name='adresse_zipc',
            field=models.CharField(blank=True, max_length=5, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact1_fname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prénom du contact 1'),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact1_lname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom du contact 1'),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact1_phone_fixe',
            field=models.CharField(blank=True, max_length=12, verbose_name='Téléphone fixe du contact 1'),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact1_phone_port',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone portable du contact 1'),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact1_relation',
            field=models.CharField(blank=True, choices=[('PR', 'Parent'), ('FR', 'Fratrie'), ('PA', 'Partenaire'), ('PC', 'Proche de confiance')], max_length=2, verbose_name='Relation du contact 1'),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact2_fname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prénom du contact 2'),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact2_lname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom du contact 2'),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact2_phone_fixe',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone fixe du contact 2'),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact2_phone_port',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone portable du contact 2'),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact2_relation',
            field=models.CharField(blank=True, choices=[('PR', 'Parent'), ('FR', 'Fratrie'), ('PA', 'Partenaire'), ('PC', 'Proche de confiance')], max_length=2, verbose_name='Relation du contact 2'),
        ),
        migrations.AddField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('AB', 'AB')], max_length=2, verbose_name='Groupe Sanguin'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_fixe',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone fixe'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_port',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone portable'),
        ),
        migrations.AddField(
            model_name='patient',
            name='rhesus_sanguin',
            field=models.CharField(blank=True, choices=[('-', '-'), ('+', '+')], max_length=2, verbose_name='Rhésus Sanguin'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='statut_compl',
            field=models.CharField(blank=True, choices=[('H', 'Homonyme'), ('F', 'Fictive'), ('D', 'Douteuse')], max_length=1, verbose_name="Statut d'identité complémentaire"),
        ),
    ]
